### ISSUE TITLE
Howto flash the device?

### ISSUE THREAD

**Issue by lubeda** [aptonline/PixelIt_Ulanzi#1]
A very nice project, pixelIt givees a lot worth to the device!!!

But, how to flash your firmware to it?

**Comment by aptonline** [comment]
No firmware binaries are currently supplied as part of this fork so the best way to install would be to compile and install the code in [Visual Studio Code](https://code.visualstudio.com). You will need:

- Visual Studio Code
- Platformio extension installed
- A clone of this project

It’s also important to install the file system as well so you are able to save config changes.

After the device has been flashed you can continue to use the [official PixelIt docs](https://pixelit-project.github.io/firmware.html#setup) to complete the setup and configuration.

I'll add a detailed build guide to the wiki in the future.

**Comment by lubeda** [comment]
Sure, but how do I flash it on the device, via USB or is there a way via wifi or may I open the case and connect to the pins of the tsp-chip?

**Comment by aptonline** [comment]
Visual Studio Code with the aforementioned Platformio extension will allow you to flash over USB. Once flashed with PixelIt there is a built in updater via the web ui but I have never used to update the Ulanzi version of the firmware, something to investigate.

**Comment by wsbtak** [comment]
@lubeda - you will need the CH340 Drivers USB Drivers to be able to flash it with VS Code or with any ESP32 flasher.

**Comment by lubeda** [comment]
Thanks, i know. Flashing with pixelit works
