### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by jekader** [aptonline/PixelIt_Ulanzi#2]
First of all, I want to thank you for porting PixelIt to the TC001! I flashed mine, over the OEM firmware and everything went smooth. The device even retained WiFi settings from the old firmware! Brightness control works, so do the buttons.

The only issue I see is that the settings I change don't seem to take any effect and the SAVE CONFIG button is always greyed out in the web UI. Also, the serial console prints this from time to time:

`[105570][E][vfs_api.cpp:24] open(): File system is not mounted`

Is this a known limitation or just some bug on my side? I did a factory reset to ensure leftovers of the OEM config don't interfere yet the result is still the same. 

Built the firmware from commit [477611c](https://github.com/aptonline/PixelIt_Ulanzi/commit/477611c6ae9e6be5a9b8c1a8d5a6121f071d75f5) - the latest one as of writing this.

**Comment by wsbtak** [comment]
Sort of know issue - be sure you have the "data" folder while compiling the firmware
![image](https://user-images.githubusercontent.com/125366691/219960398-02dd5348-ee26-40df-b774-f286942a91ff.png)

As second build and upload the FileSystem binary and factory reset one more time:
![image](https://user-images.githubusercontent.com/125366691/219960473-8a705c32-db51-44fc-ad75-9a79344c9a9f.png)

**Comment by jekader** [comment]
Thanks for the hint! 

The data folder is part of this repo so it was present during the build:
https://github.com/aptonline/PixelIt_Ulanzi/tree/main/data

In any case, I've cleaned the workspace and uploaded the image as instructed.
This time I did see a different result:

```
Building in release mode
Building FS image from 'data' directory to .pio/build/ESP32DEV/spiffs.bin
```

The FS image was created and saving settings now works as it should.
